ARG TAG=latest
ARG IMAGE_NAMESPACE=ghcr.io/noobping
FROM ${IMAGE_NAMESPACE}/workstation:${TAG}

LABEL org.opencontainers.image.title="Sway"
LABEL org.opencontainers.image.description="a Sway desktop bootable container"

RUN set -euxo pipefail; \
  rpm-ostree install -y \
    bemenu \
    brightnessctl \
    clipman \
    dmenu \
    fontawesome-6-free-fonts \
    foot \
    i3status \
    jq \
    libnotify \
    mako \
    pass \
    pass-otp \
    pavucontrol \
    playerctl \
    pulseaudio-utils \
    qt5ct \
    sway \
    swayidle \
    swaylock \
    wl-clipboard \
    wofi \
    xdg-desktop-portal-wlr; \
  if ! rpm-ostree install -y i3status-rust; then \
    printf '%s\n' '#!/usr/bin/env bash' 'exec /usr/bin/i3status' > /usr/local/bin/i3status-rs; \
    chmod 0755 /usr/local/bin/i3status-rs; \
  fi; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  mkdir -p /etc/skel/.config/sway; \
  ostree container commit

COPY config env i3rs-config.toml *.sh /etc/skel/.config/sway/

RUN set -euxo pipefail; \
  chmod 0644 \
    /etc/skel/.config/sway/config \
    /etc/skel/.config/sway/env \
    /etc/skel/.config/sway/i3rs-config.toml; \
  find /etc/skel/.config/sway -type f -name '*.sh' -exec chmod 0755 '{}' +; \
  if grep -q '^XSession=' /var/lib/AccountsService/default; then \
    sed -i 's/^XSession=.*/XSession=sway/' /var/lib/AccountsService/default; \
  else \
    printf '%s\n' 'XSession=sway' >> /var/lib/AccountsService/default; \
  fi; \
  ostree container commit
