ARG IMAGE_NAMESPACE=ghcr.io/noobping
ARG TAG=latest
FROM ${IMAGE_NAMESPACE}/vm:${TAG}

LABEL org.opencontainers.image.title="Minecraft VM"
LABEL org.opencontainers.image.description="KVM guest for Minecraft Java and Bedrock servers"

COPY containers /etc/containers/systemd
COPY minecraft.nft /etc/nftables/rules/20-minecraft.nft
COPY --chmod=0755 bin/ /usr/bin/
COPY --chmod=0755 backup-prepare /usr/libexec/infrastructure/backup-prepare
COPY --chmod=0755 backup-finish /usr/libexec/infrastructure/backup-finish

RUN ostree container commit
