http://ipa.nick.nas {
    redir https://ipa.nick.nas{uri} permanent
}

https://ipa.nick.nas {
    tls internal

    reverse_proxy https://127.0.0.1:8443 {
        transport http {
            tls_insecure_skip_verify
            tls_server_name ipa.nick.nas
        }
    }
}

:443 {
    @ipa path /ipa /ipa/* /domain /domain/*
    handle @ipa {
        uri strip_prefix /ipa
        uri strip_prefix /domain
        redir https://ipa.nick.nas{uri} permanent
    }

    @nextcloud path /nextcloud /nextcloud/* /cloud /cloud/*
    handle @nextcloud {
        uri strip_prefix /nextcloud
        uri strip_prefix /cloud
        redir http://{host}:8081{uri} permanent
    }

    @gitlab path /git /git/* /gitlab /gitlab/*
    handle @gitlab {
        uri strip_prefix /git
        uri strip_prefix /gitlab
        redir http://{host}:8929{uri} permanent
    }

    @jellyfin path /jellyfin /jellyfin/* /music /music/*
    handle @jellyfin {
        uri strip_prefix /jellyfin
        uri strip_prefix /music
        redir http://{host}:8096{uri} permanent
    }

    redir https://{host}:9090{uri} permanent
}
:80 {
    @ipa path /ipa /ipa/* /domain /domain/*
    handle @ipa {
        uri strip_prefix /ipa
        uri strip_prefix /domain
        redir https://ipa.nick.nas{uri} permanent
    }

    @nextcloud path /nextcloud /nextcloud/* /cloud /cloud/*
    handle @nextcloud {
        uri strip_prefix /nextcloud
        uri strip_prefix /cloud
        redir http://{host}:8081{uri} permanent
    }

    @gitlab path /git /git/* /gitlab /gitlab/*
    handle @gitlab {
        uri strip_prefix /git
        uri strip_prefix /gitlab
        redir http://{host}:8929{uri} permanent
    }

    @jellyfin path /jellyfin /jellyfin/* /music /music/*
    handle @jellyfin {
        uri strip_prefix /jellyfin
        uri strip_prefix /music
        redir http://{host}:8096{uri} permanent
    }

    redir https://{host}:9090{uri} permanent
}
