FROM quay.io/fedora/fedora-coreos:stable

LABEL org.opencontainers.image.title="NAS"
LABEL org.opencontainers.image.description="Nick's bootable container"

RUN set -euxo pipefail; \
  rpm-ostree override remove nfs-utils-coreos; \
  rpm-ostree install -y \
    libvirt qemu-kvm pcp-zeroconf smartmontools \
    cockpit-system cockpit-ostree cockpit-podman cockpit-machines cockpit-storaged cockpit-files cockpit-networkmanager cockpit-sosreport cockpit-kdump cockpit-selinux \
    power-profiles-daemon upower nut \
    toolbox git; \

  ln -s /var/srv/git /git; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  mkdir -p \
  /etc/nftables/rules \
  /etc/modules-load.d \
  /etc/polkit-1/rules.d \
  /etc/systemd/system/multi-user.target.wants; \
  ostree container commit

COPY todo.sh /usr/bin/todo
COPY caddy.conf /etc/caddy.conf
COPY containers /etc/containers/systemd
COPY fstab.txt /etc/fstab
COPY libvirtd.conf /etc/libvirt/libvirtd.conf
COPY mdadm.conf /etc/mdadm.conf
COPY polkit.rules /etc/polkit-1/rules.d/50-libvirt-access.rules
COPY nftables /etc/nftables/rules
COPY bashrc.sh /etc/bashrc2

RUN set -euxo pipefail; \
  chmod -R 0600 /etc/nftables/rules; \
  grep -qE 'elements\s*=\s*\{[^}]*\bhttp\b' /etc/nftables/main.nft \
  || sed -i 's/elements\s*=\s*{\([^}]*\)}/elements = {\1, http, https}/' /etc/nftables/main.nft; \

  mv /etc/bashrc /etc/bashrc1; \
  cat /etc/bashrc{1,2} > /etc/bashrc; \
  rm /etc/bashrc1 /etc/bashrc2; \
  ostree container commit