FROM ghcr.io/noobping/ips:latest

LABEL org.opencontainers.image.title="NAS"
LABEL org.opencontainers.image.description="a bootable container"

RUN set -euxo pipefail; \
  if rpm -q nfs-utils-coreos >/dev/null 2>&1; then \
    rpm-ostree override remove nfs-utils-coreos; \
  fi; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN rpm-ostree install -y \
    libvirt qemu-kvm pcp-zeroconf smartmontools \
    cockpit-system cockpit-ostree cockpit-podman cockpit-machines cockpit-storaged cockpit-files cockpit-networkmanager cockpit-sosreport cockpit-kdump cockpit-selinux \
    gssproxy \
    power-profiles-daemon upower nut \
    toolbox git; \

  ln -s /var/srv/git /git; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  mkdir -p \
  /etc/nftables/rules \
  /etc/modules-load.d \
  /etc/polkit-1/rules.d \
  /etc/ups \
  /etc/systemd/system/multi-user.target.wants \
  /etc/systemd/system/timers.target.wants \
  /usr/libexec/infrastructure \
  /usr/share/infrastructure/uptime-kuma \
  /usr/share/infrastructure/freeradius \
  /var/lib/suricata \
  /var/log/suricata; \
  ostree container commit

COPY todo.sh /usr/bin/todo
COPY caddy.conf /etc/caddy.conf
COPY containers /etc/containers/systemd
COPY freeipa-bootstrap-radius /usr/libexec/infrastructure/freeipa-bootstrap-radius
COPY freeipa-bootstrap-radius.service /etc/systemd/system/freeipa-bootstrap-radius.service
COPY freeipa-prepare /usr/libexec/infrastructure/freeipa-prepare
COPY freeipa-prepare.service /etc/systemd/system/freeipa-prepare.service
COPY freeradius /usr/share/infrastructure/freeradius
COPY freeradius-prepare /usr/libexec/infrastructure/freeradius-prepare
COPY freeradius-prepare.service /etc/systemd/system/freeradius-prepare.service
COPY gogs-prepare /usr/libexec/infrastructure/gogs-prepare
COPY libvirtd.conf /etc/libvirt/libvirtd.conf
COPY localhost-registry.conf /etc/containers/registries.conf.d/10-localhost-registry.conf
COPY mdadm.conf /etc/mdadm.conf
COPY nut-configure /usr/libexec/infrastructure/nut-configure
COPY nut-configure.service /etc/systemd/system/nut-configure.service
COPY nut.env.example /etc/ups/nut.env.example
COPY polkit.rules /etc/polkit-1/rules.d/50-libvirt-access.rules
COPY nftables /etc/nftables/rules
COPY suricata.nft /etc/nftables/suricata.nft
COPY uptime/config.json /usr/share/infrastructure/uptime-kuma/
COPY uptime/bootstrap /usr/libexec/infrastructure/uptime-kuma-bootstrap
COPY uptime/bootstrap.js /usr/libexec/infrastructure/uptime-kuma-bootstrap.js
COPY uptime/bootstrap.service /etc/systemd/system/uptime-kuma-bootstrap.service

RUN set -euxo pipefail; \
  chmod -R 0600 /etc/nftables/rules; \
  find /etc/containers/systemd -type f -name '*.container' -exec chmod 0644 '{}' ';'; \
  chmod 0755 /usr/libexec/infrastructure/gogs-prepare; \
  awk '/set allowed_tcp_dports[[:space:]]*\{/{flag=1} flag{print} /^\t*\}/{if(flag){exit}}' /etc/nftables/main.nft \
  | grep -q '\<http\>' \
  || sed -i '/set allowed_tcp_dports[[:space:]]*{/,/}/{/elements = {/ s/}/, http, https}/;}' /etc/nftables/main.nft; \
  grep -q 'include "/etc/nftables/rules/\\*.nft"' /etc/nftables/main.nft \
  || sed -i '/tcp dport @allowed_tcp_dports accept/i\        include "/etc/nftables/rules/*.nft"' /etc/nftables/main.nft; \
  grep -q 'include "/etc/nftables/suricata.nft"' /etc/nftables/main.nft \
  || printf '\ninclude "/etc/nftables/suricata.nft"\n' >> /etc/nftables/main.nft; \
  ln -sf /usr/lib/systemd/system/libvirtd.service \
    /etc/systemd/system/multi-user.target.wants/libvirtd.service; \
  ln -sf /usr/lib/systemd/system/virtlockd.service \
    /etc/systemd/system/multi-user.target.wants/virtlockd.service; \
  ln -sf /usr/lib/systemd/system/virtlogd.service \
    /etc/systemd/system/multi-user.target.wants/virtlogd.service; \
  ln -sf /usr/lib/systemd/system/power-profiles-daemon.service \
    /etc/systemd/system/multi-user.target.wants/power-profiles-daemon.service; \
  ln -sf /usr/lib/systemd/system/upower.service \
    /etc/systemd/system/multi-user.target.wants/upower.service; \
  ln -sf /etc/systemd/system/nut-configure.service \
    /etc/systemd/system/multi-user.target.wants/nut-configure.service; \
  ln -sf /etc/systemd/system/uptime-kuma-bootstrap.service \
    /etc/systemd/system/multi-user.target.wants/uptime-kuma-bootstrap.service; \
  ostree container commit
