on:
  pre-commit: [check]
  pre-push: [check]
  pre-receive: [check]

pipelines:
  check:
    jobs:
      just:
        just: check-just
      whitespace:
        just: check-whitespace
      shell:
        just: check-shell
      workstation:
        just: check-workstation

  online-images:
    needs: [check]
    jobs:
      build:
        just: online::stable

  online-media:
    needs: [check]
    jobs:
      build:
        just: online::media

  online:
    needs: [online-images, online-media]

  next:
    needs: [check]
    jobs:
      build:
        just: online::next

  offline:
    needs: [check]
    jobs:
      build:
        just: offline-build

  offline-workstation:
    needs: [check]
    jobs:
      build:
        just: offline-workstation-build

  offline-nas:
    needs: [check]
    jobs:
      build:
        just: offline-nas-build

  offline-sway:
    needs: [check]
    jobs:
      build:
        just: offline-sway-build

  release:
    needs: [online]
    jobs:
      publish:
        just: online::release

  image-task:
    jobs:
      build:
        just: online::image-task

  manifest-preflight:
    jobs:
      verify:
        just: online::manifest-preflight

  manifest-task:
    jobs:
      publish:
        just: online::manifest-task

  gitlab-manifest-task:
    jobs:
      publish:
        just: online::gitlab-manifest-task

  media-task:
    jobs:
      build:
        just: online::media-task

  gitlab-media-publish:
    jobs:
      publish:
        just: online::gitlab-media-publish

  release-assets:
    jobs:
      publish:
        just: online::release-assets

  gitlab-release-assets:
    jobs:
      publish:
        just: online::gitlab-release-assets
