variant: fcos
version: 1.6.0

passwd:
  users:
    - name: core
      should_exist: false

storage:
  files:
    - path: /etc/locale.conf
      mode: 0644
      contents:
        inline: |
          LANG=nl_NL.UTF-8

    - path: /etc/vconsole.conf
      mode: 0644
      contents:
        inline: |
          KEYMAP=us
          XKBLAYOUT=us
          XKBVARIANT=intl

    - path: /etc/X11/xorg.conf.d/00-keyboard.conf
      mode: 0644
      contents:
        inline: |
          Section "InputClass"
            Identifier "keyboard-all"
            MatchIsKeyboard "on"
            Option "XkbLayout" "us"
            Option "XkbVariant" "intl"
          EndSection

  links:
    - path: /etc/localtime
      target: /usr/share/zoneinfo/Europe/Amsterdam
      overwrite: true

systemd:
  units:
    - name: zincati.service
      enabled: true

    - name: podman.socket
      enabled: true

    - name: nftables.service
      enabled: true

    - name: podman-auto-update.timer
      enabled: true

    - name: systemd-timesyncd.service
      enabled: true

    - name: fwupd-refresh.service
      enabled: true
      contents: |
        [Unit]
        Description=Refresh firmware metadata and check for updates
        Wants=network-online.target
        After=network-online.target

        [Service]
        Type=oneshot
        Restart=on-failure
        RestartSec=30s
        StartLimitIntervalSec=0
        ExecStart=/usr/bin/fwupdmgr refresh --force
        ExecStart=/usr/bin/fwupdmgr get-updates

        [Install]
        WantedBy=multi-user.target

    - name: fwupd-update-shutdown.service
      enabled: true
      contents: |
        [Unit]
        Description=Apply firmware updates at shutdown
        DefaultDependencies=no
        Before=shutdown.target reboot.target halt.target
        ConditionACPower=true

        [Service]
        Type=oneshot
        TimeoutStartSec=0
        ExecStart=/usr/bin/fwupdmgr update -y || true

        [Install]
        WantedBy=halt.target reboot.target shutdown.target
