variant: fcos
version: 1.6.0

passwd:
  users:
    - name: core
      should_exist: false

storage:
  links:
    - path: /etc/localtime
      target: /usr/share/zoneinfo/Europe/Amsterdam
      overwrite: true

  files:
    - path: /etc/sysconfig/nftables.conf
      mode: 0600
      overwrite: true
      contents:
        inline: |
          include "/etc/nftables/main.nft"

    - path: /usr/local/sbin/rebase-to-bootc
      mode: 0755
      overwrite: true
      contents:
        local: ./butane/rebase-to-bootc

systemd:
  units:
    - name: nftables.service
      enabled: true

    - name: rpm-ostreed.service
      enabled: true

    - name: podman.socket
      enabled: true

    - name: podman-auto-update.timer
      enabled: true

    - name: systemd-timesyncd.service
      enabled: true
