variant: fcos
version: 1.6.0

passwd:
  users:
    - name: core
      should_exist: false

storage:
  files:
    - path: /etc/hostname
      mode: 0440
      contents:
        inline: |
          workstation

systemd:
  units:
    - name: zincati.service
      enabled: true

    - name: podman.socket
      enabled: true

    - name: nftables.service
      enabled: true

    - name: podman-auto-update.timer
      enabled: true

    - name: set-timezone.service
      enabled: true
      contents: |
        [Unit]
        Description=Set timezone to Europe/Amsterdam
        After=network.target

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/timedatectl set-timezone Europe/Amsterdam

        [Install]
        WantedBy=multi-user.target

    - name: systemd-timesyncd.service
      enabled: true

    - name: fwupd-refresh.service
      enabled: true
      contents: |
        [Unit]
        Description=Refresh firmware metadata and check for updates
        Wants=network-online.target
        After=network-online.target

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/fwupdmgr refresh --force
        ExecStart=/usr/bin/fwupdmgr get-updates

        [Install]
        WantedBy=multi-user.target

    - name: fwupd-update-shutdown.service
      enabled: true
      contents: |
        [Unit]
        Description=Apply firmware updates at shutdown
        DefaultDependencies=no
        Before=shutdown.target reboot.target halt.target
        ConditionACPower=true

        [Service]
        Type=oneshot
        TimeoutStartSec=0
        ExecStart=/usr/bin/fwupdmgr update -y || true

        [Install]
        WantedBy=halt.target reboot.target shutdown.target
