variant: fcos
version: 1.6.0

passwd:
  users:
    - name: core
      should_exist: false

storage:
  links:
    - path: /etc/localtime
      target: /usr/share/zoneinfo/Europe/Amsterdam
      overwrite: true

  files:    
    - path: /etc/nftables.conf
      mode: 0644
      overwrite: true
      contents:
        inline: |
          #!/usr/sbin/nft -f
          table inet filter {
            chain input {
              type filter hook input priority 0;
              iif lo accept
              ct state established,related accept
              include "/etc/nftables.d/*.nft"
              reject with icmpx type admin-prohibited
            }
          }

  directories:
    - path: /etc/nftables.d

systemd:
  units:
    - name: nftables.service
      enabled: true

    - name: zincati.service
      enabled: true

    - name: rpm-ostreed.service
      enabled: true

    - name: podman.socket
      enabled: true

    - name: podman-auto-update.timer
      enabled: true

    - name: systemd-timesyncd.service
      enabled: true

    - name: fwupd-refresh.service
      enabled: true
      contents: |
        [Unit]
        Description=Refresh firmware metadata and check for updates
        Wants=network-online.target
        After=network-online.target

        [Service]
        Type=oneshot
        Restart=on-failure
        RestartSec=30s
        StartLimitIntervalSec=0
        ExecStart=/usr/bin/fwupdmgr refresh --force
        ExecStart=/usr/bin/fwupdmgr get-updates

        [Install]
        WantedBy=multi-user.target

    - name: fwupd-update-shutdown.service
      enabled: true
      contents: |
        [Unit]
        Description=Apply firmware updates at shutdown
        DefaultDependencies=no
        Before=shutdown.target reboot.target halt.target
        ConditionACPower=true

        [Service]
        Type=oneshot
        TimeoutStartSec=0
        ExecStart=/usr/bin/fwupdmgr update -y || true

        [Install]
        WantedBy=halt.target reboot.target shutdown.target
