ARG TAG=latest
FROM registry.fedoraproject.org/fedora:latest AS pkgs
RUN dnf -y install dnf-plugins-core \
  && dnf repoquery --available --qf '%{name}\n' \
  | sort -u \
  | grep -E '(^linux-firmware$|^[[:alnum:]_.+-]+-firmware$)' \
  | grep -vE '^(gnome-firmware)$' \
  > /tmp/firmware-packages.txt \
  && wc -l /tmp/firmware-packages.txt

FROM ghcr.io/noobping/ips:${TAG}
LABEL org.opencontainers.image.title="Workstation"
LABEL org.opencontainers.image.description="a bootable container"
ARG REBASE_IMAGE_BASE=ostree-image-signed:docker://ghcr.io/noobping/

COPY --from=pkgs /tmp/firmware-packages.txt /tmp/firmware-packages.txt
RUN xargs -r rpm-ostree install -y < /tmp/firmware-packages.txt
RUN set -euxo pipefail; \
  if rpm -q nfs-utils-coreos >/dev/null 2>&1; then \
    rpm-ostree override remove nfs-utils-coreos; \
  fi; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  rpm-ostree install -y \
    cachefilesd \
    NetworkManager-wifi NetworkManager-bluetooth NetworkManager-openvpn firewalld \
    fapolicyd fapolicyd-selinux \
    accountsservice \
    aemu libvirt qemu-kvm android-tools \
    gssproxy \
    power-profiles-daemon upower nut \
    avahi bluez cups cups-browsed cups-filters cups-filters-driverless cups-pk-helper \
    dconf dbus-daemon gutenprint-cups hplip ipp-usb nss-mdns samba-client \
    sane-airscan sane-backends sane-backends-drivers-scanners \
    system-config-printer system-config-printer-applet system-config-printer-udev \
    toolbox git \
    mesa-dri-drivers switcheroo-control virglrenderer \
    libhid hidapi openrgb-udev-rules \
    steam-devices; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  rpm-ostree install -y \
    gdm ibus ibus-mozc \
    glibc-all-langpacks google-noto-color-emoji-fonts google-noto-sans-cjk-fonts fontconfig \
    gnome-backgrounds gnome-control-center gnome-disk-utility gnome-initial-setup \
    gnome-keyring gnome-menus gnome-session gnome-shell \
    xdg-desktop-portal xdg-desktop-portal-gtk \
    pipewire wireplumber \
    plymouth plymouth-theme-spinner \
    ptyxis; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  rpm-ostree install -y \
    nautilus nautilus-python python3-pygit2 nautilus-gsconnect sushi \
    seahorse-nautilus tnef-nautilus papers-nautilus \
    pcsc-lite pcsc-lite-ccid opensc gnupg2 gnupg2-scdaemon yubikey-manager \
    flatpak flatpak-spawn \
    fuse fuse-libs \
    tracker-miners ffmpegthumbnailer gstreamer1-libav gstreamer1-plugin-openh264; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  rpm-ostree override remove gnome-tour; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  mkdir -p \
    /etc/NetworkManager/system-connections \
    /etc/fapolicyd/rules.d \
    /etc/firewalld/zones \
    /etc/polkit-1/rules.d \
    /etc/recommended \
    /etc/sysconfig \
    /etc/ups \
    /etc/systemd/system/graphical.target.wants \
    /etc/systemd/system/multi-user.target.wants \
    /etc/systemd/system/sockets.target.wants \
    /etc/systemd/system/sysinit.target.wants \
    /etc/systemd/system/timers.target.wants \
    /usr/libexec/infrastructure \
    /usr/share/gnome-background-properties \
    /var/lib/AccountsService

# COPY *.nmconnection /etc/NetworkManager/system-connections/
COPY aliases.sh /etc/profile.d/
# COPY alternative.desktop /usr/share/applications/
COPY alternative.policy /usr/share/polkit-1/actions/dev.noobping.workstation.alternative.policy
COPY alternative.sh /usr/bin/alternative
COPY alternative-root.sh /usr/libexec/infrastructure/alternative-root
COPY background.png /usr/share/backgrounds/wallpaper.png
COPY background.xml /usr/share/gnome-background-properties/noobping.xml
COPY cachefilesd.conf /etc/cachefilesd.conf
COPY certs/ /etc/pki/ca-trust/source/anchors/
COPY extensions.txt /etc/recommended/extensions
COPY fapolicyd-deny-user-writable-exec.rules /etc/fapolicyd/rules.d/30-deny-user-writable-exec.rules
COPY fapolicyd-flatpak-sync /usr/libexec/infrastructure/fapolicyd-flatpak-sync
COPY fapolicyd-flatpak-sync.path /etc/systemd/system/fapolicyd-flatpak-sync.path
COPY fapolicyd-flatpak-sync.service /etc/systemd/system/fapolicyd-flatpak-sync.service
COPY fapolicyd-flatpak-sync.timer /etc/systemd/system/fapolicyd-flatpak-sync.timer
COPY firewall.xml /etc/firewalld/zones/public.xml
COPY suricata-direct.xml /etc/firewalld/direct.xml
COPY libvirtd.conf /etc/libvirt/libvirtd.conf
COPY nut-netclient-configure /usr/libexec/infrastructure/nut-netclient-configure
COPY nut-netclient-configure.service /etc/systemd/system/nut-netclient-configure.service
COPY nut-netclient.env.example /etc/ups/netclient.env.example
COPY polkit-printers.rules /etc/polkit-1/rules.d/50-printer-access.rules
COPY polkit.rules /etc/polkit-1/rules.d/50-libvirt-access.rules
COPY profile.conf /var/lib/AccountsService/default
COPY profile.png /usr/share/pixmaps/faces/noobping.png
COPY recommended.desktop /etc/xdg/autostart/
COPY recommended.desktop /usr/share/applications/
COPY recommended.sh /usr/bin/recommended
COPY skel /etc/skel

RUN set -euxo pipefail; \
  update-ca-trust; \

  mkdir -p /etc/skel/.config; \

  chmod +x /etc/profile.d/aliases.sh; \
  chmod +x /usr/bin/recommended; \
  chmod +x /usr/bin/alternative; \
  chmod +x /usr/libexec/infrastructure/alternative-root; \
  chmod +x /usr/libexec/infrastructure/fapolicyd-flatpak-sync; \
  chmod +x /usr/libexec/infrastructure/nut-netclient-configure; \

  # chmod 0600 /etc/NetworkManager/system-connections/*.nmconnection; \
  chmod 0644 /etc/firewalld/direct.xml; \
  chmod 0644 /etc/polkit-1/rules.d/50-libvirt-access.rules; \
  fapolicyd-cli --check-config; \

  rm -f /etc/resolv.conf; \
  ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf; \

  sed -i 's/tcp dport @allowed_tcp_dports accept/# &/' /etc/nftables/main.nft; \
  echo DefaultZone=public > /etc/firewalld/firewalld.conf; \

  echo "${REBASE_IMAGE_BASE}desktop:latest" > /etc/recommended/base; \

  ln -sf /usr/lib/systemd/system/gdm.service \
    /etc/systemd/system/graphical.target.wants/gdm.service; \
  ln -sf /usr/lib/systemd/system/gdm.service \
    /etc/systemd/system/display-manager.service; \
  ln -sf /usr/lib/systemd/system/graphical.target \
    /etc/systemd/system/default.target; \
  ln -sf /usr/lib/systemd/system/libvirtd.service \
    /etc/systemd/system/multi-user.target.wants/libvirtd.service; \
  ln -sf /usr/lib/systemd/system/virtlockd.service \
    /etc/systemd/system/multi-user.target.wants/virtlockd.service; \
  ln -sf /usr/lib/systemd/system/virtlogd.service \
    /etc/systemd/system/multi-user.target.wants/virtlogd.service; \
  ln -sf /usr/lib/systemd/system/cachefilesd.service \
    /etc/systemd/system/multi-user.target.wants/cachefilesd.service; \
  ln -sf /usr/lib/systemd/system/firewalld.service \
    /etc/systemd/system/multi-user.target.wants/firewalld.service; \
  ln -sf /etc/systemd/system/nut-netclient-configure.service \
    /etc/systemd/system/multi-user.target.wants/nut-netclient-configure.service; \
  ln -sf /usr/lib/systemd/system/avahi-daemon.service \
    /etc/systemd/system/multi-user.target.wants/avahi-daemon.service; \
  ln -sf /usr/lib/systemd/system/cups-browsed.service \
    /etc/systemd/system/multi-user.target.wants/cups-browsed.service; \
  ln -sf /usr/lib/systemd/system/ipp-usb.service \
    /etc/systemd/system/multi-user.target.wants/ipp-usb.service; \
  ln -sf /usr/lib/systemd/system/switcheroo-control.service \
    /etc/systemd/system/graphical.target.wants/switcheroo-control.service; \
  ln -sf /usr/lib/systemd/system/power-profiles-daemon.service \
    /etc/systemd/system/graphical.target.wants/power-profiles-daemon.service; \
  ln -sf /usr/lib/systemd/system/upower.service \
    /etc/systemd/system/graphical.target.wants/upower.service; \
  ln -sf /usr/lib/systemd/system/pcscd.socket \
    /etc/systemd/system/sockets.target.wants/pcscd.socket; \
  ln -sf /usr/lib/systemd/system/cups.socket \
    /etc/systemd/system/sockets.target.wants/cups.socket; \
  ln -sf /usr/lib/systemd/system/plymouth-start.service \
    /etc/systemd/system/sysinit.target.wants/plymouth-start.service; \
  ln -sf /dev/null /etc/systemd/system/nftables.service; \

  printf '%s\n' "INITIAL_SETUP_ENABLE=YES" > /etc/sysconfig/initial-setup; \
  ostree container commit
