FROM quay.io/fedora/fedora-coreos:stable
LABEL org.opencontainers.image.title="Workstation" \
  org.opencontainers.image.description="Nick's bootable container"
RUN rpm-ostree install -y cachefilesd \
    NetworkManager-wifi \
    accountsservice \
    aemu libvirt qemu-kvm \
    android-tools \
    cups bluez dconf-editor \
    dbus-daemon \
    flatpak flatpak-spawn \
    fuse fuse-libs gvfs-fuse \
    gdm \
    glibc-langpack-en glibc-langpack-nl \
    gnome-backgrounds \
    gnome-control-center \
    gnome-disk-utility \
    gnome-initial-setup \
    gnome-keyring \
    gnome-network-displays \
    gnome-session \
    gnome-shell \
    libhid hidapi \
    mesa-dri-drivers \
    nautilus nautilus-python python3-pygit2 \
    openrgb-udev-rules \
    pipewire \
    steam-devices \
    toolbox git \
    wireplumber \
    xdg-desktop-portal \
    xdg-desktop-portal-gtk && \
  rm -rf /var/cache/* && \
  ostree container commit
RUN printf "LANG=nl_NL.UTF-8\n" > /etc/locale.conf && \
  ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime && \
  ostree container commit
  RUN printf "KEYMAP=us\nXKBLAYOUT=us\nXKBVARIANT=intl\n" > /etc/vconsole.conf && \
  mkdir -p /etc/X11/xorg.conf.d && \
  printf 'Section "InputClass"\n\
Identifier "keyboard-all"\n\
MatchIsKeyboard "on"\n\
Option "XkbLayout" "us"\n\
Option "XkbVariant" "intl"\n\
EndSection\n' > /etc/X11/xorg.conf.d/00-keyboard.conf && \
  ostree container commit
RUN mkdir -p /etc/sysconfig /var/lib/AccountsService && \
    printf "INITIAL_SETUP_ENABLE=YES\n" > /etc/sysconfig/initial-setup && \
    printf "[User]\nLanguage=nl_NL.UTF-8\n" > /var/lib/AccountsService/default && \
    ostree container commit
COPY cachefilesd.conf /etc/cachefilesd.conf
RUN ln -sf /usr/lib/systemd/system/graphical.target /etc/systemd/system/default.target && \
  mkdir -p /etc/systemd/system/graphical.target.wants && \
  ln -sf /usr/lib/systemd/system/gdm.service /etc/systemd/system/graphical.target.wants/gdm.service && \
  ostree container commit
RUN rm -f /etc/resolv.conf && \
  ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf && \
  mkdir -p /etc/skel/.bashrc.d && \
  ostree container commit
COPY aliases/ /etc/skel/.bashrc.d/
COPY background.png /usr/share/backgrounds/
COPY profile.png /usr/share/pixmaps/faces/nick.png
RUN set -euo pipefail; \
  url="$(curl -fsSL https://api.github.com/repos/noobping/PasswordStore/releases/latest \
    | grep -m1 '"browser_download_url":' \
    | grep 'AppImage"' \
    | cut -d '"' -f 4 \
    | tr -d '\r')"; \
  echo "Downloading: $url"; \
  curl -fL "$url" -o /etc/skel/passwordstore.AppImage; \
  chmod +x /etc/skel/passwordstore.AppImage; \
  ostree container commit