FROM quay.io/fedora/fedora-coreos:stable
LABEL org.opencontainers.image.title="Workstation"
LABEL org.opencontainers.image.description="Nick's bootable container"
RUN rpm-ostree install -y cachefilesd \
    NetworkManager-wifi \
    accountsservice \
    aemu libvirt qemu-kvm \
    android-tools \
    cups bluez dconf-editor \
    dbus-daemon \
    flatpak flatpak-spawn \
    fuse fuse-libs gvfs-fuse jq curl \
    gdm \
    glibc-all-langpacks \
    gnome-backgrounds \
    gnome-control-center \
    gnome-disk-utility \
    gnome-initial-setup \
    gnome-keyring \
    gnome-session \
    gnome-shell \
    libhid hidapi \
    mesa-dri-drivers switcheroo-control \
    nautilus nautilus-python python3-pygit2 \
    openrgb-udev-rules \
    pipewire \
    plymouth \
    power-profiles-daemon upower nut \
    steam-devices \
    toolbox git \
    wireplumber \
    xdg-desktop-portal \
    xdg-desktop-portal-gtk && \
  rm -rf /var/cache/* && \
  ostree container commit
RUN printf "LANG=nl_NL.UTF-8\n" > /etc/locale.conf && \
  ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime && \
  ostree container commit
  RUN printf "KEYMAP=us\nXKBLAYOUT=us\nXKBVARIANT=intl\n" > /etc/vconsole.conf && \
  mkdir -p /etc/X11/xorg.conf.d && \
  printf 'Section "InputClass"\n\
Identifier "keyboard-all"\n\
MatchIsKeyboard "on"\n\
Option "XkbLayout" "us"\n\
Option "XkbVariant" "intl"\n\
EndSection\n' > /etc/X11/xorg.conf.d/00-keyboard.conf && \
  ostree container commit
RUN mkdir -p /etc/sysconfig /var/lib/AccountsService && \
    printf "INITIAL_SETUP_ENABLE=YES\n" > /etc/sysconfig/initial-setup && \
    printf "[User]\nLanguage=nl_NL.UTF-8\n" > /var/lib/AccountsService/default && \
    ostree container commit
COPY cachefilesd.conf /etc/cachefilesd.conf
RUN ln -sf /usr/lib/systemd/system/graphical.target /etc/systemd/system/default.target && \
  mkdir -p /etc/systemd/system/graphical.target.wants && \
  ln -sf /usr/lib/systemd/system/gdm.service /etc/systemd/system/graphical.target.wants/gdm.service && \
  ostree container commit
COPY profile.png /usr/share/pixmaps/faces/nick.png
COPY background.png /usr/share/backgrounds/nick-wallpaper.png
RUN rm -f /etc/resolv.conf && \
  ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf && \
  mkdir -p /etc/dconf/db/local.d /usr/share/gnome-background-properties && \
  printf "<?xml version=\"1.0\"?>\n\
<!DOCTYPE wallpapers SYSTEM \"gnome-wp-list.dtd\">\n\
<wallpapers>\n\
  <wallpaper deleted=\"false\">\n\
    <name>Nick's wallpaper</name>\n\
    <filename>/usr/share/backgrounds/nick-wallpaper.png</filename>\n\
    <options>zoom</options>\n\
  </wallpaper>\n\
</wallpapers>\n" > /usr/share/gnome-background-properties/nick.xml && \
  dconf update && \
  mkdir -p /var/lib/AccountsService && \
  printf "[User]\nIcon=/usr/share/pixmaps/faces/nick.png\n" > /var/lib/AccountsService/default && \
  mkdir -p /etc/skel/.bashrc.d && \
  ostree container commit
COPY skel /etc/skel
COPY passwordstore.sh /passwordstore.sh
RUN chmod +x /passwordstore.sh && /passwordstore.sh && rm /passwordstore.sh && ostree container commit
