Debug 0

GenericExecuteSynth \
"printf %s '$DATA' | /opt/piper-tts/bin/python -m piper --data-dir /usr/share/piper-voices --model '$VOICE' --output-raw --sentence-silence 0.15 | pw-play --raw --rate 22050 --channels 1 --format s16 -"

GenericCmdDependency "/opt/piper-tts/bin/python"
GenericCmdDependency "pw-play"

GenericSoundIconFolder "/usr/share/sounds/sound-icons/"

DefaultVoice "nl_NL-ronnie-medium"

AddVoice "nl" "MALE1" "nl_NL-ronnie-medium"
AddVoice "nl" "MALE2" "nl_NL-ronnie-medium"
AddVoice "nl" "MALE3" "nl_NL-ronnie-medium"
AddVoice "nl" "FEMALE1" "nl_NL-ronnie-medium"
AddVoice "nl" "FEMALE2" "nl_NL-ronnie-medium"
AddVoice "nl" "FEMALE3" "nl_NL-ronnie-medium"
AddVoice "nl" "CHILD_MALE" "nl_NL-ronnie-medium"
AddVoice "nl" "CHILD_FEMALE" "nl_NL-ronnie-medium"

AddVoice "nl-NL" "MALE1" "nl_NL-ronnie-medium"
AddVoice "nl-NL" "MALE2" "nl_NL-ronnie-medium"
AddVoice "nl-NL" "MALE3" "nl_NL-ronnie-medium"
AddVoice "nl-NL" "FEMALE1" "nl_NL-ronnie-medium"
AddVoice "nl-NL" "FEMALE2" "nl_NL-ronnie-medium"
AddVoice "nl-NL" "FEMALE3" "nl_NL-ronnie-medium"
AddVoice "nl-NL" "CHILD_MALE" "nl_NL-ronnie-medium"
AddVoice "nl-NL" "CHILD_FEMALE" "nl_NL-ronnie-medium"

AddVoice "nl_NL" "MALE1" "nl_NL-ronnie-medium"
AddVoice "nl_NL" "MALE2" "nl_NL-ronnie-medium"
AddVoice "nl_NL" "MALE3" "nl_NL-ronnie-medium"
AddVoice "nl_NL" "FEMALE1" "nl_NL-ronnie-medium"
AddVoice "nl_NL" "FEMALE2" "nl_NL-ronnie-medium"
AddVoice "nl_NL" "FEMALE3" "nl_NL-ronnie-medium"
AddVoice "nl_NL" "CHILD_MALE" "nl_NL-ronnie-medium"
AddVoice "nl_NL" "CHILD_FEMALE" "nl_NL-ronnie-medium"

AddVoice "en" "MALE1" "en_US-lessac-high"
AddVoice "en" "MALE2" "en_US-lessac-high"
AddVoice "en" "MALE3" "en_US-lessac-high"
AddVoice "en" "FEMALE1" "en_US-lessac-high"
AddVoice "en" "FEMALE2" "en_US-lessac-high"
AddVoice "en" "FEMALE3" "en_US-lessac-high"
AddVoice "en" "CHILD_MALE" "en_US-lessac-high"
AddVoice "en" "CHILD_FEMALE" "en_US-lessac-high"

AddVoice "en-US" "MALE1" "en_US-lessac-high"
AddVoice "en-US" "MALE2" "en_US-lessac-high"
AddVoice "en-US" "MALE3" "en_US-lessac-high"
AddVoice "en-US" "FEMALE1" "en_US-lessac-high"
AddVoice "en-US" "FEMALE2" "en_US-lessac-high"
AddVoice "en-US" "FEMALE3" "en_US-lessac-high"
AddVoice "en-US" "CHILD_MALE" "en_US-lessac-high"
AddVoice "en-US" "CHILD_FEMALE" "en_US-lessac-high"

AddVoice "en_US" "MALE1" "en_US-lessac-high"
AddVoice "en_US" "MALE2" "en_US-lessac-high"
AddVoice "en_US" "MALE3" "en_US-lessac-high"
AddVoice "en_US" "FEMALE1" "en_US-lessac-high"
AddVoice "en_US" "FEMALE2" "en_US-lessac-high"
AddVoice "en_US" "FEMALE3" "en_US-lessac-high"
AddVoice "en_US" "CHILD_MALE" "en_US-lessac-high"
AddVoice "en_US" "CHILD_FEMALE" "en_US-lessac-high"
