ARG TAG=latest
ARG IMAGE_NAMESPACE=ghcr.io/noobping
FROM registry.fedoraproject.org/fedora:latest AS pkgs
RUN dnf -y install dnf-plugins-core \
  && dnf repoquery --available --qf '%{name}\n' \
  | sort -u \
  | grep -E '(^linux-firmware$|^[[:alnum:]_.+-]+-firmware$)' \
  | grep -vE '^(gnome-firmware|python3-virt-firmware)$' \
  > /tmp/firmware-packages.txt \
  && wc -l /tmp/firmware-packages.txt

FROM ${IMAGE_NAMESPACE}/ips:${TAG}
LABEL org.opencontainers.image.title="OPA"
LABEL org.opencontainers.image.description="a bootable Cinnamon desktop container"

COPY --from=pkgs /tmp/firmware-packages.txt /tmp/firmware-packages.txt
RUN xargs -r rpm-ostree install -y < /tmp/firmware-packages.txt
RUN set -euxo pipefail; \
  if rpm -q nfs-utils-coreos >/dev/null 2>&1; then \
    rpm-ostree override remove nfs-utils-coreos; \
  fi; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  rpm-ostree install -y \
    NetworkManager-wifi NetworkManager-bluetooth firewalld \
    accountsservice dbus-daemon \
    power-profiles-daemon upower \
    avahi bluez cups cups-browsed cups-filters cups-filters-driverless cups-pk-helper \
    gutenprint-cups hplip ipp-usb nss-mdns samba-client \
    sane-airscan sane-backends sane-backends-drivers-scanners \
    system-config-printer system-config-printer-udev \
    mesa-dri-drivers switcheroo-control \
    glibc-all-langpacks google-noto-color-emoji-fonts google-noto-sans-cjk-fonts fontconfig \
    cinnamon cinnamon-control-center cinnamon-screensaver nemo \
    lightdm slick-greeter slick-greeter-cinnamon \
    xdg-desktop-portal xdg-desktop-portal-gtk \
    pipewire pipewire-alsa pipewire-pulseaudio wireplumber \
    plymouth plymouth-theme-spinner \
    gvfs gvfs-gphoto2 gvfs-mtp gvfs-smb gvfs-archive \
    flatpak flatpak-spawn \
    git rclone \
    ffmpegthumbnailer gstreamer1-libav gstreamer1-plugin-openh264; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  mkdir -p \
    /etc/NetworkManager/system-connections \
    /etc/firewalld/zones \
    /etc/polkit-1/rules.d \
    /etc/recommended \
    /etc/systemd/system/graphical.target.wants \
    /etc/systemd/system/multi-user.target.wants \
    /etc/systemd/system/sockets.target.wants \
    /etc/systemd/system/sysinit.target.wants \
    /etc/systemd/system/timers.target.wants \
    /usr/libexec/infrastructure

COPY flathub.txt /etc/recommended/flathub
COPY firewall.xml /etc/firewalld/zones/public.xml
COPY suricata-direct.xml /etc/firewalld/direct.xml
COPY polkit-printers.rules /etc/polkit-1/rules.d/50-printer-access.rules
COPY system-flatpaks /usr/libexec/infrastructure/system-flatpaks
COPY system-flatpaks.service /etc/systemd/system/system-flatpaks.service
COPY update-system-flatpaks.service /etc/systemd/system/update-system-flatpaks.service
COPY update-system-flatpaks.timer /etc/systemd/system/update-system-flatpaks.timer

RUN set -euxo pipefail; \
  chmod +x /usr/libexec/infrastructure/system-flatpaks; \
  chmod 0644 /etc/firewalld/direct.xml; \
  rm -f /etc/resolv.conf; \
  ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf; \
  sed -i 's/tcp dport @allowed_tcp_dports accept/# &/' /etc/nftables/main.nft; \
  echo DefaultZone=public > /etc/firewalld/firewalld.conf; \
  ln -sf /usr/lib/systemd/system/lightdm.service \
    /etc/systemd/system/graphical.target.wants/lightdm.service; \
  ln -sf /usr/lib/systemd/system/lightdm.service \
    /etc/systemd/system/display-manager.service; \
  ln -sf /usr/lib/systemd/system/graphical.target \
    /etc/systemd/system/default.target; \
  ln -sf /usr/lib/systemd/system/firewalld.service \
    /etc/systemd/system/multi-user.target.wants/firewalld.service; \
  ln -sf /etc/systemd/system/system-flatpaks.service \
    /etc/systemd/system/multi-user.target.wants/system-flatpaks.service; \
  ln -sf /etc/systemd/system/update-system-flatpaks.service \
    /etc/systemd/system/multi-user.target.wants/update-system-flatpaks.service; \
  ln -sf /usr/lib/systemd/system/avahi-daemon.service \
    /etc/systemd/system/multi-user.target.wants/avahi-daemon.service; \
  ln -sf /usr/lib/systemd/system/cups-browsed.service \
    /etc/systemd/system/multi-user.target.wants/cups-browsed.service; \
  ln -sf /usr/lib/systemd/system/ipp-usb.service \
    /etc/systemd/system/multi-user.target.wants/ipp-usb.service; \
  ln -sf /usr/lib/systemd/system/switcheroo-control.service \
    /etc/systemd/system/graphical.target.wants/switcheroo-control.service; \
  ln -sf /usr/lib/systemd/system/power-profiles-daemon.service \
    /etc/systemd/system/graphical.target.wants/power-profiles-daemon.service; \
  ln -sf /usr/lib/systemd/system/upower.service \
    /etc/systemd/system/graphical.target.wants/upower.service; \
  ln -sf /usr/lib/systemd/system/cups.socket \
    /etc/systemd/system/sockets.target.wants/cups.socket; \
  ln -sf /usr/lib/systemd/system/plymouth-start.service \
    /etc/systemd/system/sysinit.target.wants/plymouth-start.service; \
  ln -sf /etc/systemd/system/update-system-flatpaks.timer \
    /etc/systemd/system/timers.target.wants/update-system-flatpaks.timer; \
  ln -sf /dev/null /etc/systemd/system/nftables.service; \
  ostree container commit
