[Unit]
Wants=network-online.target
Requires=artifacts-prepare.service
After=network-online.target artifacts-prepare.service
RequiresMountsFor=/var/lib/containers /var/srv/ssd /var/srv/docs /var/srv/music /var/srv/books /sysroot/ostree/deploy/fedora-coreos/var

[Service]
ExecStartPre=/usr/sbin/setsebool nfs_export_all_ro on
ExecStartPre=/usr/sbin/setsebool nfs_export_all_rw on
