[Unit]
Wants=network-online.target
Requires=artifacts-prepare.service nfs-root-prepare.service
After=network-online.target artifacts-prepare.service nfs-root-prepare.service

[Service]
ExecStartPre=/usr/sbin/setsebool nfs_export_all_ro on
ExecStartPre=/usr/sbin/setsebool nfs_export_all_rw on
