apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    app.kubernetes.io/part-of: infrastructure-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/part-of: infrastructure-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: office
  labels:
    app.kubernetes.io/part-of: infrastructure-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: paperless
  labels:
    app.kubernetes.io/part-of: infrastructure-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: infrastructure-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
  labels:
    app.kubernetes.io/part-of: infrastructure-cluster

