ARG FCOS_STREAM=stable
ARG POLICY_IMAGE=ghcr.io/noobping/policy:latest
FROM ${POLICY_IMAGE} AS policy

FROM quay.io/fedora/fedora-coreos:${FCOS_STREAM}

LABEL org.opencontainers.image.title="IPS"
LABEL org.opencontainers.image.description="a inline IPS base image"

RUN set -euxo pipefail; \
  dnf install -y \
    clamav clamav-data clamd clamav-freshclam \
    suricata \
    tuned upower; \
  dnf clean all; \
  mkdir -p \
    /etc/sysctl.d \
    /etc/systemd/system/clamav-freshclam.service.d \
    /etc/systemd/system/clamd@scan.service.d \
    /etc/systemd/system/multi-user.target.wants \
    /etc/systemd/system/timers.target.wants \
    /etc/systemd/system/gssproxy.service.d \
    /etc/systemd/system/suricata.service.d \
    /usr/share/clamav \
    /usr/share/suricata \
    /usr/libexec/infrastructure \
    /usr/share/containers/systemd; \
  if test -d /sysroot/ostree/repo; then ostree container commit; fi

COPY clamav-clamonacc.service /etc/systemd/system/clamav-clamonacc.service
COPY clamav-freshclam.service.d/10-prepare.conf /etc/systemd/system/clamav-freshclam.service.d/10-prepare.conf
COPY clamav-inotify.conf /etc/sysctl.d/90-clamav-inotify.conf
COPY --from=policy / /usr/lib/infrastructure-policy/rootfs/
COPY *-prepare.container /usr/share/containers/systemd/
COPY state-roots.conf /usr/lib/tmpfiles.d/infrastructure-ips.conf
COPY --chmod=0755 bin/ /usr/libexec/infrastructure/
COPY clamd.scan.conf /etc/clamd.d/scan.conf
COPY clamd@scan.service.d/10-prepare.conf /etc/systemd/system/clamd@scan.service.d/10-prepare.conf
COPY freshclam.conf /etc/freshclam.conf
COPY gssproxy.service.d/10-infrastructure.conf /etc/systemd/system/gssproxy.service.d/10-infrastructure.conf
COPY ips.yaml /etc/suricata/ips.yaml
COPY suricata-update.service /etc/systemd/system/suricata-update.service
COPY suricata-update.timer /etc/systemd/system/suricata-update.timer
COPY suricata.service.d/10-inline.conf /etc/systemd/system/suricata.service.d/10-inline.conf

# OCI runtime mount targets must exist before this tree lives under immutable /usr.
RUN set -euxo pipefail; \
  touch \
    /usr/lib/infrastructure-policy/rootfs/etc/hostname \
    /usr/lib/infrastructure-policy/rootfs/etc/hosts \
    /usr/lib/infrastructure-policy/rootfs/etc/resolv.conf; \
  chmod 0644 \
    /etc/clamd.d/scan.conf \
    /etc/freshclam.conf \
    /etc/sysctl.d/90-clamav-inotify.conf \
    /etc/systemd/system/clamav-clamonacc.service \
    /etc/systemd/system/clamav-freshclam.service.d/10-prepare.conf \
    /etc/systemd/system/clamd@scan.service.d/10-prepare.conf; \
  install -d -o clamupdate -g virusgroup -m 0755 /var/lib/clamav; \
  install -d -o clamupdate -g virusgroup -m 0775 /var/log/clamav; \
  cp -a /var/lib/clamav/. /usr/share/clamav/; \
  chown -R root:root /usr/share/clamav; \
  /usr/libexec/infrastructure/suricata-sync-rules; \
  cp -a /var/lib/suricata/rules/. /usr/share/suricata/rules/; \
  rm -rf /var/lib/suricata/rules; \
  test -s /usr/share/suricata/rules/suricata.rules; \
  chown -R root:root /usr/share/suricata; \
  grep -q '^include: /etc/suricata/ips.yaml$' /etc/suricata/suricata.yaml \
  || printf '\ninclude: /etc/suricata/ips.yaml\n' >> /etc/suricata/suricata.yaml; \
  if grep -q '^OPTIONS=' /etc/sysconfig/suricata; then \
    sed -i 's|^OPTIONS=.*|OPTIONS="-q 0"|' /etc/sysconfig/suricata; \
  else \
    printf '%s\n' 'OPTIONS="-q 0"' >> /etc/sysconfig/suricata; \
  fi; \
  ln -sf /usr/lib/systemd/system/clamav-freshclam.service \
    /etc/systemd/system/multi-user.target.wants/clamav-freshclam.service; \
  ln -sf /usr/lib/systemd/system/clamd@.service \
    /etc/systemd/system/multi-user.target.wants/clamd@scan.service; \
  ln -sf /etc/systemd/system/clamav-clamonacc.service \
    /etc/systemd/system/multi-user.target.wants/clamav-clamonacc.service; \
  ln -sf /usr/lib/systemd/system/suricata.service \
    /etc/systemd/system/multi-user.target.wants/suricata.service; \
  ln -sf /usr/lib/systemd/system/tuned.service \
    /etc/systemd/system/multi-user.target.wants/tuned.service; \
  ln -sf /usr/lib/systemd/system/upower.service \
    /etc/systemd/system/multi-user.target.wants/upower.service; \
  ln -sf /etc/systemd/system/suricata-update.timer \
    /etc/systemd/system/timers.target.wants/suricata-update.timer; \
  if test -d /sysroot/ostree/repo; then ostree container commit; fi

RUN if ! test -d /sysroot/ostree/repo; then bootc container lint; fi
