DatabaseDirectory /var/lib/clamav
UpdateLogFile /var/log/clamav/freshclam.log
LogTime yes
DatabaseOwner clamupdate
Checks 24
DNSDatabaseInfo current.cvd.clamav.net
DatabaseMirror database.clamav.net
ScriptedUpdates yes
NotifyClamd /etc/clamd.d/scan.conf
