LogFile /var/log/clamav/clamd.log
LogTime yes
LogSyslog yes
PidFile /run/clamd.scan/clamd.pid
TemporaryDirectory /var/tmp
DatabaseDirectory /var/lib/clamav

LocalSocket /run/clamd.scan/clamd.sock
LocalSocketGroup virusgroup
LocalSocketMode 660
FixStaleSocket yes

User clamscan
SelfCheck 3600
MaxThreads 12
MaxQueue 100

OnAccessIncludePath /run/media
OnAccessIncludePath /tmp
OnAccessIncludePath /var/home
OnAccessIncludePath /var/mnt
OnAccessIncludePath /var/opt
OnAccessIncludePath /var/roothome
OnAccessIncludePath /var/srv
OnAccessIncludePath /var/tmp
OnAccessIncludePath /var/usrlocal
OnAccessExcludeUname clamscan
OnAccessPrevention yes
OnAccessExtraScanning yes
OnAccessMaxThreads 12
