FROM quay.io/fedora/fedora-coreos:stable

LABEL org.opencontainers.image.title="IPS"
LABEL org.opencontainers.image.description="Nick's inline IPS base image"

RUN set -euxo pipefail; \
  rpm-ostree install -y \
    suricata; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  mkdir -p \
    /etc/systemd/system/multi-user.target.wants \
    /etc/systemd/system/timers.target.wants \
    /etc/systemd/system/gssproxy.service.d \
    /etc/systemd/system/suricata.service.d \
    /usr/libexec/infrastructure; \
  ostree container commit

COPY gssproxy-prepare.service /etc/systemd/system/gssproxy-prepare.service
COPY gssproxy-prepare /usr/libexec/infrastructure/gssproxy-prepare
COPY gssproxy.service.d/10-infrastructure.conf /etc/systemd/system/gssproxy.service.d/10-infrastructure.conf
COPY ips.yaml /etc/suricata/ips.yaml
COPY suricata-sync-rules /usr/libexec/infrastructure/suricata-sync-rules
COPY suricata-update.service /etc/systemd/system/suricata-update.service
COPY suricata-update.timer /etc/systemd/system/suricata-update.timer
COPY suricata.service.d/10-inline.conf /etc/systemd/system/suricata.service.d/10-inline.conf

RUN set -euxo pipefail; \
  chmod 0755 /usr/libexec/infrastructure/gssproxy-prepare; \
  chmod 0755 /usr/libexec/infrastructure/suricata-sync-rules; \
  install -d -o suricata -g suricata -m 0750 /var/lib/suricata /var/log/suricata; \
  /usr/libexec/infrastructure/suricata-sync-rules; \
  grep -q '^include: /etc/suricata/ips.yaml$' /etc/suricata/suricata.yaml \
  || printf '\ninclude: /etc/suricata/ips.yaml\n' >> /etc/suricata/suricata.yaml; \
  if grep -q '^OPTIONS=' /etc/sysconfig/suricata; then \
    sed -i 's|^OPTIONS=.*|OPTIONS="-q 0"|' /etc/sysconfig/suricata; \
  else \
    printf '%s\n' 'OPTIONS="-q 0"' >> /etc/sysconfig/suricata; \
  fi; \
  ln -sf /usr/lib/systemd/system/suricata.service \
    /etc/systemd/system/multi-user.target.wants/suricata.service; \
  ln -sf /etc/systemd/system/suricata-update.timer \
    /etc/systemd/system/timers.target.wants/suricata-update.timer; \
  ostree container commit
