ARG FCOS_STREAM=stable
FROM quay.io/fedora/fedora-coreos:${FCOS_STREAM}

LABEL org.opencontainers.image.title="IPS"
LABEL org.opencontainers.image.description="a inline IPS base image"

RUN set -euxo pipefail; \
  rpm-ostree install -y \
    clamav clamav-data clamd clamav-freshclam \
    suricata \
    tuned upower; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  mkdir -p \
    /etc/nftables/rules \
    /etc/sysctl.d \
    /etc/systemd/system/clamav-freshclam.service.d \
    /etc/systemd/system/clamd@scan.service.d \
    /etc/systemd/system/gssproxy.service.d \
    /etc/systemd/system/suricata.service.d \
    /usr/share/clamav \
    /usr/share/suricata \
    /usr/libexec/infrastructure; \
  ostree container commit

COPY clamav-clamonacc.service /etc/systemd/system/clamav-clamonacc.service
COPY clamav-freshclam.service.d/10-prepare.conf /etc/systemd/system/clamav-freshclam.service.d/10-prepare.conf
COPY clamav-inotify.conf /etc/sysctl.d/90-clamav-inotify.conf
COPY clamav-prepare.service /etc/systemd/system/clamav-prepare.service
COPY --chmod=0755 clamav-prepare /usr/libexec/infrastructure/clamav-prepare
COPY clamd.scan.conf /etc/clamd.d/scan.conf
COPY clamd@scan.service.d/10-prepare.conf /etc/systemd/system/clamd@scan.service.d/10-prepare.conf
COPY freshclam.conf /etc/freshclam.conf
COPY gssproxy-prepare.service /etc/systemd/system/gssproxy-prepare.service
COPY --chmod=0755 gssproxy-prepare /usr/libexec/infrastructure/gssproxy-prepare
COPY gssproxy.service.d/10-infrastructure.conf /etc/systemd/system/gssproxy.service.d/10-infrastructure.conf
COPY ips.yaml /etc/suricata/ips.yaml
COPY suricata-prepare.service /etc/systemd/system/suricata-prepare.service
COPY --chmod=0755 suricata-prepare /usr/libexec/infrastructure/suricata-prepare
COPY --chmod=0755 suricata-sync-rules /usr/libexec/infrastructure/suricata-sync-rules
COPY suricata-update.service /etc/systemd/system/suricata-update.service
COPY suricata-update.timer /etc/systemd/system/suricata-update.timer
COPY suricata.service.d/10-inline.conf /etc/systemd/system/suricata.service.d/10-inline.conf

RUN set -euxo pipefail; \
  install -d -o clamupdate -g virusgroup -m 0755 /var/lib/clamav; \
  install -d -o clamupdate -g virusgroup -m 0775 /var/log/clamav; \
  cp -a /var/lib/clamav/. /usr/share/clamav/; \
  chown -R root:root /usr/share/clamav; \
  /usr/libexec/infrastructure/clamav-prepare; \
  install -d -o suricata -g suricata -m 0750 /var/lib/suricata /var/log/suricata; \
  /usr/libexec/infrastructure/suricata-sync-rules; \
  mv /var/lib/suricata/rules /usr/share/suricata/rules; \
  chown -R root:root /usr/share/suricata; \
  grep -q '^include: /etc/suricata/ips.yaml$' /etc/suricata/suricata.yaml \
  || printf '\ninclude: /etc/suricata/ips.yaml\n' >> /etc/suricata/suricata.yaml; \
  grep -q 'include "/etc/nftables/rules/\\*.nft"' /etc/nftables/main.nft \
  || sed -i '/tcp dport @allowed_tcp_dports accept/i\        include "/etc/nftables/rules/*.nft"' /etc/nftables/main.nft; \
  if grep -q '^OPTIONS=' /etc/sysconfig/suricata; then \
    sed -i 's|^OPTIONS=.*|OPTIONS="-q 0"|' /etc/sysconfig/suricata; \
  else \
    printf '%s\n' 'OPTIONS="-q 0"' >> /etc/sysconfig/suricata; \
  fi; \
  systemctl enable \
    clamav-prepare.service clamav-freshclam.service clamd@scan.service \
    clamav-clamonacc.service suricata.service suricata-update.timer \
    tuned.service; \
  ostree container commit
