FROM registry.fedoraproject.org/fedora:latest AS pkgs
RUN dnf -y install dnf-plugins-core \
  && dnf repoquery --available --qf '%{name}\n' \
  | sort -u \
  | grep -E '(^linux-firmware$|^[[:alnum:]_.+-]+-firmware$)' \
  | grep -vE '^(gnome-firmware)$' \
  > /tmp/firmware-packages.txt \
  && wc -l /tmp/firmware-packages.txt

FROM ghcr.io/noobping/ips:latest
LABEL org.opencontainers.image.title="Cinnamon"
LABEL org.opencontainers.image.description="Nick's locked-down Cinnamon bootable container"

COPY --from=pkgs /tmp/firmware-packages.txt /tmp/firmware-packages.txt
RUN xargs -r rpm-ostree install -y < /tmp/firmware-packages.txt
RUN set -euxo pipefail; \
  if rpm -q nfs-utils-coreos >/dev/null 2>&1; then \
    rpm-ostree override remove nfs-utils-coreos; \
  fi; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  rpm-ostree install -y \
    NetworkManager-wifi NetworkManager-bluetooth NetworkManager-openvpn firewalld \
    accountsservice \
    bluez cups dconf dbus-daemon flatpak \
    fapolicyd fapolicyd-selinux \
    gdm \
    power-profiles-daemon upower \
    mesa-dri-drivers switcheroo-control \
    cinnamon cinnamon-control-center cinnamon-session \
    nemo xed xreader \
    xorg-x11-server-Xwayland \
    xdg-desktop-portal xdg-desktop-portal-gtk \
    pipewire wireplumber \
    plymouth plymouth-theme-spinner \
    glibc-all-langpacks google-noto-color-emoji-fonts google-noto-sans-cjk-fonts fontconfig; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

RUN set -euxo pipefail; \
  mkdir -p \
    /etc/environment.d \
    /etc/firewalld/zones \
    /etc/gdm \
    /etc/systemd/system/graphical.target.wants \
    /etc/systemd/system/multi-user.target.wants \
    /etc/systemd/system/sysinit.target.wants \
    /usr/libexec/infrastructure

COPY firewall.xml /etc/firewalld/zones/public.xml
COPY fapolicyd-flatpak-sync /usr/libexec/infrastructure/fapolicyd-flatpak-sync
COPY flatpak-exports.conf /etc/environment.d/60-flatpak-exports.conf
COPY gdm-custom.conf /etc/gdm/custom.conf
COPY suricata-direct.xml /etc/firewalld/direct.xml

RUN set -euxo pipefail; \
  chmod 0755 /usr/libexec/infrastructure/fapolicyd-flatpak-sync; \
  chmod 0644 /etc/environment.d/60-flatpak-exports.conf; \
  chmod 0644 /etc/firewalld/direct.xml; \
  chmod 0644 /etc/firewalld/zones/public.xml; \
  chmod 0644 /etc/gdm/custom.conf; \
  if [ -e /etc/environment ]; then \
    grep -qxF 'XDG_DATA_DIRS=/var/lib/flatpak/exports/share:/usr/local/share:/usr/share' /etc/environment || \
      printf '%s\n' 'XDG_DATA_DIRS=/var/lib/flatpak/exports/share:/usr/local/share:/usr/share' >> /etc/environment; \
  else \
    install -m 0644 /etc/environment.d/60-flatpak-exports.conf /etc/environment; \
  fi; \
  rm -f /etc/resolv.conf; \
  ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf; \
  sed -i 's/tcp dport @allowed_tcp_dports accept/# &/' /etc/nftables/main.nft; \
  sed -i '/^\[Desktop Entry\]/a Hidden=true' /usr/share/applications/cinnamon-settings-users.desktop; \
  sed -i '/^\[Desktop Entry\]/a Hidden=true' /usr/share/xsessions/cinnamon.desktop; \
  sed -i '/^\[Desktop Entry\]/a Hidden=true' /usr/share/xsessions/cinnamon2d.desktop; \
  printf '%s\n' 'DefaultZone=public' > /etc/firewalld/firewalld.conf; \
  ln -sf /usr/lib/systemd/system/gdm.service \
    /etc/systemd/system/graphical.target.wants/gdm.service; \
  ln -sf /usr/lib/systemd/system/gdm.service \
    /etc/systemd/system/display-manager.service; \
  ln -sf /usr/lib/systemd/system/graphical.target \
    /etc/systemd/system/default.target; \
  ln -sf /usr/lib/systemd/system/firewalld.service \
    /etc/systemd/system/multi-user.target.wants/firewalld.service; \
  ln -sf /usr/lib/systemd/system/fapolicyd.service \
    /etc/systemd/system/multi-user.target.wants/fapolicyd.service; \
  ln -sf /usr/lib/systemd/system/switcheroo-control.service \
    /etc/systemd/system/graphical.target.wants/switcheroo-control.service; \
  ln -sf /usr/lib/systemd/system/power-profiles-daemon.service \
    /etc/systemd/system/graphical.target.wants/power-profiles-daemon.service; \
  ln -sf /usr/lib/systemd/system/upower.service \
    /etc/systemd/system/graphical.target.wants/upower.service; \
  ln -sf /usr/lib/systemd/system/plymouth-start.service \
    /etc/systemd/system/sysinit.target.wants/plymouth-start.service; \
  ln -sf /dev/null /etc/systemd/system/sshd.service; \
  ln -sf /dev/null /etc/systemd/system/getty@.service; \
  ln -sf /dev/null /etc/systemd/system/serial-getty@.service; \
  ln -sf /dev/null /etc/systemd/system/emergency.service; \
  ln -sf /dev/null /etc/systemd/system/rescue.service; \
  ln -sf /dev/null /etc/systemd/system/debug-shell.service; \
  ln -sf /dev/null /etc/systemd/system/nftables.service; \
  ostree container commit
