ARG IMAGE_NAMESPACE=ghcr.io/noobping
ARG TAG=latest
ARG POLICY_IMAGE=ghcr.io/noobping/policy:latest
FROM ${POLICY_IMAGE} AS policy

FROM ${IMAGE_NAMESPACE}/ips:${TAG}

LABEL org.opencontainers.image.title="NAS"
LABEL org.opencontainers.image.description="a bootable container"

RUN set -euxo pipefail; \
  if rpm -q nfs-utils-coreos >/dev/null 2>&1; then \
    dnf remove -y --no-autoremove nfs-utils-coreos; \
  fi; \
  dnf clean all; \
  if test -d /sysroot/ostree/repo; then ostree container commit; fi

RUN set -euxo pipefail; \
  dnf install -y \
    coreos-installer ignition-validate jq \
    libvirt nfs-utils qemu-kvm pcp-zeroconf smartmontools \
    cockpit-system cockpit-ostree cockpit-podman cockpit-machines cockpit-storaged cockpit-files cockpit-networkmanager cockpit-sosreport cockpit-kdump cockpit-selinux \
    gssproxy \
    nut \
    toolbox git tmux; \

  ln -s /var/srv/git /git; \
  dnf clean all; \
  mkdir -p \
  /etc/exports.d \
  /etc/nftables/rules \
  /etc/nfs.conf.d \
  /etc/modules-load.d \
  /etc/polkit-1/rules.d \
  /etc/ups \
  /etc/containers/registries.conf.d \
  /etc/systemd/system/multi-user.target.wants \
  /etc/systemd/system/nfs-server.service.d \
  /etc/systemd/system/timers.target.wants \
  /usr/libexec/infrastructure \
  /usr/share/containers/systemd \
  /var/lib/suricata \
  /var/log/suricata \
  /var/www; \
  install -d -m 0755 /var/www/git; \
  ln -s /var/www/git /web; \
  if test -d /sysroot/ostree/repo; then ostree container commit; fi

COPY --chmod=0600 nftables /etc/nftables/rules
COPY --chmod=0755 bin/todo bin/vm-bridge bin/vm-deploy /usr/bin/
COPY --from=policy / /usr/lib/infrastructure-policy/rootfs/
COPY --chmod=0644 infrastructure-policy.container /usr/share/containers/systemd/
COPY --chmod=0755 bin/artifacts-prepare bin/btrfs-backup bin/nut-activate /usr/libexec/infrastructure/
COPY artifacts-prepare.service /etc/systemd/system/artifacts-prepare.service
COPY btrfs-backup.service /etc/systemd/system/btrfs-backup.service
COPY btrfs-backup.timer /etc/systemd/system/btrfs-backup.timer
COPY containers /etc/containers/systemd
COPY fstab.txt /etc/fstab
COPY libvirtd.conf /etc/libvirt/libvirtd.conf
COPY localhost-registry.conf /etc/containers/registries.conf.d/10-localhost-registry.conf
COPY mdadm.conf /etc/mdadm.conf
COPY nfs/exports /etc/exports.d/infrastructure.exports
COPY nfs/nfs.conf /etc/nfs.conf.d/infrastructure.conf
COPY nfs/nfs-root-prepare.service /etc/systemd/system/nfs-root-prepare.service
COPY nfs/nfs-server.conf /etc/systemd/system/nfs-server.service.d/10-infrastructure.conf
COPY nfs/storage.conf /usr/lib/tmpfiles.d/infrastructure-nfs.conf
COPY --chmod=0644 nut-activate.service /usr/lib/systemd/system/infrastructure-policy-nut-activate.service
COPY nut.env.example /etc/ups/nut.env.example
COPY --chmod=0644 pipeline.sh /etc/profile.d/pipeline.sh
COPY polkit.rules /etc/polkit-1/rules.d/50-libvirt-access.rules
COPY suricata.nft /etc/nftables/suricata.nft

RUN set -euxo pipefail; \
  awk '/set allowed_tcp_dports[[:space:]]*\{/{flag=1} flag{print} /^\t*\}/{if(flag){exit}}' /etc/nftables/main.nft \
  | grep -q '\<http\>' \
  || sed -i '/set allowed_tcp_dports[[:space:]]*{/,/}/{/elements = {/ s/}/, http, https}/;}' /etc/nftables/main.nft; \
  grep -q 'include "/etc/nftables/rules/\\*.nft"' /etc/nftables/main.nft \
  || sed -i '/tcp dport @allowed_tcp_dports accept/i\        include "/etc/nftables/rules/*.nft"' /etc/nftables/main.nft; \
  grep -q 'include "/etc/nftables/suricata.nft"' /etc/nftables/main.nft \
  || printf '\ninclude "/etc/nftables/suricata.nft"\n' >> /etc/nftables/main.nft; \
  ln -sf /usr/lib/systemd/system/libvirtd.service \
    /etc/systemd/system/multi-user.target.wants/libvirtd.service; \
  ln -sf /usr/lib/systemd/system/virtlockd.service \
    /etc/systemd/system/multi-user.target.wants/virtlockd.service; \
  ln -sf /usr/lib/systemd/system/virtlogd.service \
    /etc/systemd/system/multi-user.target.wants/virtlogd.service; \
  ln -sf /usr/lib/systemd/system/nfs-server.service \
    /etc/systemd/system/multi-user.target.wants/nfs-server.service; \
  ln -sf /etc/systemd/system/btrfs-backup.timer \
    /etc/systemd/system/timers.target.wants/btrfs-backup.timer; \
  if test -d /sysroot/ostree/repo; then ostree container commit; fi

RUN if ! test -d /sysroot/ostree/repo; then bootc container lint; fi
