FROM registry.fedoraproject.org/fedora:latest
LABEL org.opencontainers.image.title="Gnome Extensions CLI"
LABEL org.opencontainers.image.description="Command line tool to manage your Gnome Shell extensions"
RUN dnf -y install \
      python3-pip \
      glib2 \
      dconf \
      gsettings-desktop-schemas \
      gnome-shell \
    && dnf clean all
RUN pip3 install --no-cache-dir gnome-extensions-cli
ENTRYPOINT ["gext"]