name: check

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: pipeline-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check with Pipeline
        uses: noobping/pipeline@continuous
        with:
          arguments: |
            --cap-jobs
            3
            check
