ARG WORKSTATION_IMAGE=ghcr.io/noobping/workstation:latest
FROM ${WORKSTATION_IMAGE}
ARG REBASE_IMAGE=ostree-image-signed:docker://ghcr.io/noobping/workstation:latest
LABEL org.opencontainers.image.title="Desktop"
LABEL org.opencontainers.image.description="Nick's bootable container"
COPY extensions.txt /etc/recommended/extensions
COPY extensions.dconf /etc/recommended/settings.dconf
RUN echo "${REBASE_IMAGE}" > /etc/recommended/base \
 && ostree container commit
