FROM ghcr.io/noobping/workstation:latest
LABEL org.opencontainers.image.title="Desktop"
LABEL org.opencontainers.image.description="Nick's bootable container"
ARG REBASE_IMAGE_BASE=ostree-image-signed:docker://ghcr.io/noobping/

RUN set -euxo pipefail; \
  remove_packages=" \
    aemu libvirt libvirt-daemon-driver-lxc \
    qemu-kvm qemu-system-x86 qemu-system-aarch64 \
    qemu-device-display-virtio-gpu-gl qemu-device-display-virtio-gpu-pci-gl \
    qemu-device-display-vhost-user-gpu \
    virglrenderer \
    cachefilesd NetworkManager-openvpn \
    fuse fuse-libs \
    gnome-disk-utility gnome-menus \
    seahorse-nautilus python3-pygit2 \
    toolbox ptyxis \
    yubikey-manager \
  "; \
  installed_packages=""; \
  for package in ${remove_packages}; do \
    if rpm -q "${package}" >/dev/null 2>&1; then \
      installed_packages="${installed_packages:+${installed_packages} }${package}"; \
    else \
      echo "Skipping not-installed package: ${package}"; \
    fi; \
  done; \
  if [ -n "${installed_packages}" ]; then \
    rpm-ostree override remove ${installed_packages}; \
  fi; \
  rm -rf /var/cache/rpm-ostree /var/lib/rpm-ostree/cache /var/cache/dnf; \
  ostree container commit

COPY extensions.txt /etc/recommended/extensions
COPY extensions.dconf /etc/recommended/settings.dconf
COPY disable-appimages.sh /etc/profile.d/zz-desktop-hardening.sh

RUN set -euxo pipefail; \
    chmod 0644 /etc/profile.d/zz-desktop-hardening.sh; \
    echo "${REBASE_IMAGE_BASE}workstation:latest" > /etc/recommended/base; \
    ln -sf /usr/lib/systemd/system/fapolicyd.service \
        /etc/systemd/system/multi-user.target.wants/fapolicyd.service; \
    ln -sf /etc/systemd/system/fapolicyd-flatpak-sync.path \
        /etc/systemd/system/multi-user.target.wants/fapolicyd-flatpak-sync.path; \
    ln -sf /etc/systemd/system/fapolicyd-flatpak-sync.timer \
        /etc/systemd/system/timers.target.wants/fapolicyd-flatpak-sync.timer; \
    rm -f /etc/systemd/system/multi-user.target.wants/cachefilesd.service; \
    rm -f /etc/systemd/system/multi-user.target.wants/libvirtd.service; \
    rm -f /etc/systemd/system/multi-user.target.wants/virtlockd.service; \
    rm -f /etc/systemd/system/multi-user.target.wants/virtlogd.service; \
    ostree container commit
